"""Expert knowledge base.

For every finding type this module answers the questions an experienced packet
analyst asks: *what* was observed, *why* it typically happens (probable root
causes), what it means from each perspective (client, server, network path,
routing/control plane, application, security), how to *remediate* it now and
what to *recommend* long-term. It also carries the Wireshark display filter to
jump straight to the evidence - many taken from Chris Greer's (Packet Pioneer)
published Wireshark profiles (TCP Plain / ThreatHunt filter buttons and
colouring rules).
"""
from __future__ import annotations

from .findings import Finding


def K(title, category, protocol, severity, causes, perspectives, remediation, recommendations, filter=""):
    return {"title": title, "category": category, "protocol": protocol, "severity": severity,
            "causes": causes, "perspectives": perspectives, "remediation": remediation,
            "recommendations": recommendations, "filter": filter}


KB: dict[str, dict] = {
    # ================================================================ TCP ===
    "tcp_retransmissions": K(
        "TCP retransmissions (packet loss)", "Transport", "TCP", "high",
        ["Packet loss on the path: congested/oversubscribed link, queue drops (tail drop / AQM) on a router or firewall",
         "Duplex mismatch, bad cable/optic, CRC errors or Wi-Fi interference at layer 1/2",
         "Policer or shaper dropping bursts that exceed the committed rate",
         "Overloaded middlebox (firewall, IPS, load balancer, NAT) dropping under CPU/session pressure",
         "Receiver host dropping at the NIC ring buffer / socket buffer"],
        {"client": "The sender stalls for an RTO (min 200 ms–1 s, doubling each attempt) or for fast-retransmit round trips; the user perceives freezes and low throughput.",
         "server": "If the server is the sender, its congestion window collapses (cwnd halves on fast retransmit, resets to 1 MSS on RTO) and bulk transfers slow dramatically.",
         "network": "Loss is almost always a network-path symptom. Retransmissions seen from the sender side prove the original was lost *after* the capture point (or ACK lost on return). Capture at multiple points to bisect where loss occurs.",
         "application": "Applications see latency spikes; chatty protocols (SMB, database, RPC) multiply the delay by the number of round trips.",
         "security": "Sustained loss can also result from DoS traffic saturating links or an IPS silently dropping flagged segments."},
        ["Check interface counters (input errors, CRC, drops, overruns, output queue drops) on every hop along the path",
         "Verify speed/duplex auto-negotiation on both ends of each access link",
         "Review QoS policers/shapers and firewall/IPS drop logs for this 5-tuple",
         "Capture simultaneously at client and server side to locate the lossy segment (bisect the path)"],
        ["Implement QoS with adequate queue depth for the traffic class; consider AQM (fq_codel/WRED)",
         "Enable SACK and modern congestion control (BBR/CUBIC) on servers",
         "Monitor link utilization and error counters with alerts (SNMP/streaming telemetry)",
         "Baseline normal retransmission rate (<1%) for critical applications"],
        "tcp.analysis.retransmission || tcp.analysis.fast_retransmission"),
    "tcp_duplicate_acks": K(
        "Duplicate ACKs (receiver signalling missing data)", "Transport", "TCP", "medium",
        ["A segment was lost or re-ordered and the receiver keeps acknowledging the last in-order byte",
         "Load-balanced paths (ECMP/LAG per-packet) re-ordering segments"],
        {"client": "The receiver is healthy and telling the sender exactly what is missing (SACK blocks show what arrived).",
         "server": "The sender should fast-retransmit after 3 dup ACKs; if it doesn't, check whether SACK/fast retransmit is disabled.",
         "network": "A burst of dup ACKs pinpoints loss or reordering between capture point and receiver.",
         "application": "Brief throughput dips; usually recovered without RTO.",
         "security": "Not a security indicator on its own."},
        ["Correlate with the retransmission that follows to measure recovery time",
         "Check for per-packet load balancing on port-channels/ECMP (use per-flow hashing)"],
        ["Keep SACK enabled end-to-end; ensure middleboxes do not strip TCP options"],
        "tcp.analysis.duplicate_ack"),
    "tcp_out_of_order": K(
        "Out-of-order segments", "Transport", "TCP", "low",
        ["Multiple paths with different latency (ECMP, per-packet LAG hashing, SD-WAN path steering)",
         "Wi-Fi retransmissions at layer 2 or QoS re-queuing"],
        {"client": "Receiver must buffer and may send dup ACKs, possibly triggering needless fast retransmits.",
         "server": "Sender may retransmit spuriously, reducing its congestion window.",
         "network": "Look for asymmetric/multi-path forwarding for a single flow.",
         "application": "Minor, unless severe enough to trigger spurious retransmissions.",
         "security": "None."},
        ["Verify load-balancing hash uses the full 5-tuple (per-flow, not per-packet)"],
        ["Pin a flow to a single path; review SD-WAN packet-duplication/steering policies"],
        "tcp.analysis.out_of_order"),
    "tcp_spurious_retrans": K(
        "Spurious retransmissions", "Transport", "TCP", "low",
        ["Sender retransmitted data the receiver already acknowledged: the ACK was delayed/lost or the RTO is too aggressive",
         "Capture point after a WAN optimizer or on a mirrored port with duplicated packets"],
        {"client": "Wasted bandwidth but no data loss.", "server": "RTO estimation may be too low for this path's latency variance.",
         "network": "ACK path loss or high jitter; check the reverse direction.", "application": "Minor.", "security": "None."},
        ["Inspect the reverse (ACK) path for loss", "Check capture for duplicate packets from SPAN configuration"],
        ["Tune min RTO only if clearly too aggressive for the path"],
        "tcp.analysis.spurious_retransmission"),
    "tcp_lost_segment": K(
        "Previous segment not captured / ACKed unseen segment", "Capture", "TCP", "medium",
        ["The capture device dropped packets (SPAN oversubscription, slow disk, CPU) — not necessarily the network",
         "Capture started mid-stream or asymmetric routing sends one direction elsewhere",
         "Genuine loss upstream of the capture point (when followed by dup ACKs + retransmission)"],
        {"client": "If the receiver ACKs data we never saw (ACKed unseen), the data *did* arrive — the capture missed it.",
         "server": "No impact if ACKed unseen; real loss if dup ACKs and retransmissions follow.",
         "network": "Asymmetric routing is common across firewalls/load balancers; verify both directions traverse the capture point.",
         "application": "Analysis accuracy is reduced; throughput metrics may be understated.",
         "security": "Asymmetric flows can break stateful firewalls/IPS inspection."},
        ["If 'ACKed unseen' dominates: fix the capture (use a TAP, reduce SPAN sources, capture with dumpcap to fast disk, slice with -s)",
         "If followed by retransmissions: treat as real packet loss upstream of the capture point"],
        ["Use hardware TAPs or dedicated capture appliances for high-rate links",
         "Validate capture fidelity before drawing conclusions (the 'measure the measurement' rule)"],
        "tcp.analysis.lost_segment || tcp.analysis.ack_lost_segment"),
    "tcp_syn_no_response": K(
        "TCP SYN without SYN-ACK (connection timeout)", "Transport", "TCP", "high",
        ["Firewall/ACL/security group silently dropping (no RST, no ICMP)",
         "Server down, powered off, or wrong IP (resolved to a stale DNS record)",
         "Routing black hole: no return route, asymmetric path through stateful firewall, NAT misconfiguration",
         "Server SYN backlog full (SYN flood or accept queue overflow)"],
        {"client": "Connect() blocks through exponential SYN retries (1 s, 2 s, 4 s ...) — typically 21+ s before the application reports a timeout.",
         "server": "If the server never saw the SYN it's a path/filter problem; if it saw it, check backlog (netstat -s 'SYNs to LISTEN sockets dropped') and host firewall.",
         "network": "Silent drops point to a filtering device. Verify the forward and return route and NAT translations; trace with the 5-tuple.",
         "application": "Service appears unavailable; health checks fail; users see 'connection timed out'.",
         "security": "Could be an intentional block, or the source may be scanning closed/filtered ports."},
        ["Capture on the server side to see if the SYN arrives", "Check firewall/security-group/ACL hit counters for the 5-tuple",
         "Verify DNS returns the correct, current address", "Check routing & NAT for the return path"],
        ["Prefer REJECT (RST/ICMP) over silent DROP inside the enterprise so failures are fast and diagnosable",
         "Monitor SYN backlog and enable SYN cookies on internet-facing servers",
         "Synthetic TCP connect monitoring for critical services"],
        "tcp.flags.syn==1 && tcp.flags.ack==0 && tcp.analysis.retransmission"),
    "tcp_conn_refused": K(
        "Connection refused (SYN answered with RST)", "Transport", "TCP", "high",
        ["No process listening on the destination port (service stopped/crashed or wrong port)",
         "Host firewall or network firewall configured to REJECT with TCP RST",
         "Load balancer VIP with no healthy pool members",
         "Port scan activity (many refused ports from one source)"],
        {"client": "Fails immediately with ECONNREFUSED — fast failure, unlike a silent drop.",
         "server": "The OS (or a device spoofing it) actively rejected — check that the service is running and bound to the right IP/port (ss -lntp).",
         "network": "Check the TTL of the RST: if it differs from the server's normal TTL, a firewall/LB in the path generated it.",
         "application": "Service outage or misconfigured endpoint/port in client configuration.",
         "security": "Many refused connections from one source across ports = reconnaissance."},
        ["Verify the service is listening (ss -lntp / netstat -ano) and bound to the correct interface",
         "Compare RST TTL/IP-ID with legitimate server packets to identify the device that sent it",
         "Check load balancer pool health"],
        ["Implement service health monitoring and auto-restart", "Document service ports; validate client configuration after changes"],
        "tcp.flags.reset==1 && tcp.seq==1 && tcp.ack==1"),
    "tcp_reset_abort": K(
        "TCP connection aborted by RST mid-session", "Transport", "TCP", "medium",
        ["Application crash or abortive close (SO_LINGER 0) on one side",
         "Firewall/NAT/load-balancer idle timeout expired and the device resets or forgets the session",
         "IPS/proxy injecting RSTs to block content",
         "Data sent to a socket already closed by the peer"],
        {"client": "User sees 'connection reset by peer'; partially transferred data may be lost.",
         "server": "Check application logs at the RST timestamp for exceptions or worker restarts.",
         "network": "RSTs whose TTL/IP-ID do not match the real endpoint were injected by a middlebox.",
         "application": "Transactions fail mid-flight; retries may cause duplicates if not idempotent.",
         "security": "RST injection is a hallmark of IPS/censorship devices; also used in session hijacking attacks."},
        ["Identify who sent the RST and compare its TTL with prior packets from that host",
         "Check idle-timeout values on firewalls/NAT/LB versus application keep-alive intervals",
         "Correlate with application error logs at the same timestamp"],
        ["Use TCP or application keep-alives shorter than the smallest middlebox idle timeout",
         "Use graceful close (FIN) in applications; make operations idempotent"],
        "tcp.flags.reset==1"),
    "tcp_zero_window": K(
        "TCP zero window (receiver cannot accept data)", "Transport", "TCP", "high",
        ["The receiving application is not reading from its socket fast enough (CPU starvation, blocked thread, slow disk write)",
         "Receive buffer too small for the data rate",
         "Receiver host under memory pressure"],
        {"client": "If the client advertises zero window, the client machine/app is the bottleneck, NOT the network or server.",
         "server": "If the server advertises zero window, the server application (or its backend: disk, DB) cannot keep up.",
         "network": "The network is exonerated — the sender is flow-controlled by the receiver. Zero-window probes follow at back-off intervals.",
         "application": "Throughput stalls; the time spent at zero window is pure application/host latency.",
         "security": "Sockstress-style DoS attacks deliberately advertise zero windows to tie up server resources."},
        ["Examine the receiving host: CPU, memory, disk I/O, and the application's read loop",
         "Increase socket receive buffers / enable receive window auto-tuning",
         "Check for antivirus/DLP agents hooking the network stack on the receiver"],
        ["Profile the receiving application under load", "Monitor socket queue sizes (ss -tm Recv-Q)"],
        "tcp.analysis.zero_window || tcp.analysis.zero_window_probe"),
    "tcp_window_full": K(
        "TCP window full (sender limited by receive window)", "Transport", "TCP", "medium",
        ["Receive window smaller than the bandwidth-delay product (BDP) of the path",
         "Window scaling disabled or stripped by a middlebox, capping the window at 64 KB",
         "Receiver application reading slowly (window shrinking)"],
        {"client": "Downloads are capped at window/RTT regardless of link speed.",
         "server": "Server is ready to send more but must wait for window openings.",
         "network": "Link capacity is under-used; the limit is end-host TCP tuning, not bandwidth.",
         "application": "Large transfers (backups, file copies, replication) run far below link speed on high-latency paths.",
         "security": "None."},
        ["Compute BDP = bandwidth × RTT and compare to the advertised window",
         "Verify window scaling is negotiated in the SYN/SYN-ACK", "Increase receive buffer limits (net.ipv4.tcp_rmem / autotuning)"],
        ["Enable window scaling and autotuning on all hosts", "Test with iperf3 on the same path to confirm"],
        "tcp.analysis.window_full"),
    "tcp_low_rwin": K(
        "Low receive window advertised", "Transport", "TCP", "low",
        ["Receiver buffer nearly exhausted (slow application)", "Small static socket buffer configuration"],
        {"client": "If the client advertises it, the client is the bottleneck.", "server": "If the server advertises it, the server is slow to consume uploads.",
         "network": "Not a network problem.", "application": "Upload/download stalls.", "security": "None."},
        ["Inspect the receiving host's application and buffers"], ["Enable receive-window auto-tuning"],
        "tcp.window_size <= 2920 && tcp.flags.syn==0 && tcp.flags.reset==0"),
    "tcp_high_irtt": K(
        "High initial round-trip time (slow TCP handshake)", "Transport", "TCP", "medium",
        ["Long geographic distance / satellite / congested WAN link",
         "Overloaded server or load balancer slow to answer SYNs",
         "Bufferbloat: large queues at a congested hop add delay",
         "Traffic hair-pinned through a distant security stack or VPN concentrator"],
        {"client": "Every round-trip-bound operation (TLS handshake, HTTP request) pays this latency at least once.",
         "server": "If the server-side portion (SYN→SYN-ACK) dominates, the delay is between the capture point and the server.",
         "network": "Handshake split tells you where latency lives: SYN→SYN-ACK = capture-point-to-server path; SYN-ACK→ACK = capture-point-to-client path.",
         "application": "Chatty applications suffer most; latency × round trips = user wait.",
         "security": "Unexpected high RTT to a 'local' service may indicate traffic being redirected (MITM/hairpin)."},
        ["Compare with baseline RTT for this destination", "Check the path (traceroute/mtr) for suboptimal routing or hairpinning",
         "Check queue depths/utilization on WAN links"],
        ["Place services closer to users (CDN, regional deployment)", "Reduce application round trips (HTTP/2, connection reuse, TLS 1.3)"],
        "tcp.analysis.initial_rtt > 0.2"),
    "tcp_no_wscale": K(
        "Window scaling not negotiated", "Transport", "TCP", "low",
        ["One endpoint (or a middlebox rewriting SYNs) does not offer the window-scale option",
         "Legacy OS/embedded stack"],
        {"client": "Receive window capped at 65,535 bytes: max throughput = 64 KB / RTT (≈5 Mbps at 100 ms).",
         "server": "Same cap for data the server receives.", "network": "Firewalls/WAN optimizers sometimes strip options.",
         "application": "Bulk transfers limited on long-fat networks.", "security": "None."},
        ["Check which side omitted the option in SYN/SYN-ACK", "Check middleboxes for TCP option normalization"],
        ["Enable RFC 7323 window scaling on all hosts"], "tcp.flags.syn==1 && !tcp.options.wscale.shift"),
    "tcp_no_sack": K(
        "Selective ACK not negotiated", "Transport", "TCP", "info",
        ["An endpoint or middlebox disabled SACK"],
        {"client": "Loss recovery is slower: without SACK the sender may retransmit already received data.",
         "server": "Same.", "network": "Check for option stripping.", "application": "Worse performance under loss.", "security": "None."},
        ["Verify SACK is enabled on both hosts"], ["Keep SACK enabled end-to-end"], "tcp.flags.syn==1 && !tcp.options.sack_perm"),
    "tcp_small_mss": K(
        "Reduced TCP MSS (tunnel / encapsulation overhead)", "Transport", "TCP", "info",
        ["Path contains a tunnel (IPsec, GRE, VXLAN, PPPoE, SSL-VPN) and a device clamps the MSS",
         "Mismatched MSS between endpoints"],
        {"client": "More packets per byte transferred; slight efficiency loss.", "server": "Same.",
         "network": "MSS clamping is a healthy workaround for path-MTU reduction; lack of it causes PMTUD black holes.",
         "application": "Usually transparent.", "security": "None."},
        ["Confirm the MSS matches the smallest MTU on the path minus 40 bytes (IPv4)"],
        ["Clamp MSS on tunnel interfaces (ip tcp adjust-mss)", "Allow ICMP 'fragmentation needed' for PMTUD"],
        "tcp.options.mss_val < 1460"),
    "tcp_slow_response": K(
        "Slow application response (server think time)", "Application", "TCP", "high",
        ["Server application processing delay: slow database query, backend dependency, lock contention, GC pause",
         "Server CPU/memory saturation", "Upstream service (auth, API, storage) slow"],
        {"client": "User waits for the first byte of the response after sending the request.",
         "server": "The request was delivered and ACKed quickly, but the response took long — time spent inside the server/backends.",
         "network": "Network is exonerated when the request is ACKed promptly and no retransmissions occur during the wait.",
         "application": "This is application latency; trace the transaction through the server's logs/APM.",
         "security": "Unusually slow responses to specific requests may indicate resource-exhaustion attacks (slow queries, regex DoS)."},
        ["Use APM/logs to trace the slow request on the server", "Check backend dependencies (database, auth, storage)",
         "Correlate with server CPU/memory/GC metrics at the same time"],
        ["Set SLOs on server response time; add caching and query optimization", "Instrument backends with distributed tracing"],
        "tcp.time_delta > 1"),
    "tcp_idle_gaps": K(
        "Large TCP time gaps (delta > 1 s) inside conversations", "Application", "TCP", "low",
        ["Client/user think time, server processing time, retransmission timeouts or zero-window stalls"],
        {"client": "Gaps where the client is next to speak are client-side delays.",
         "server": "Gaps where the server is next to speak are server-side delays.",
         "network": "Gaps ending in a retransmission are network loss (RTO).",
         "application": "Attribute each gap to whose turn it was to talk — Chris Greer's 'TCP Delta' technique.",
         "security": "Beaconing malware produces very regular gaps."},
        ["Use the attributed cause on each gap to decide whether to look at client, server or network"],
        ["Add a 'TCP delta' column (tcp.time_delta) and sort descending when troubleshooting slowness"],
        "tcp.time_delta > 1"),
    "tcp_capture_point": K(
        "Capture point location (from handshake timing)", "Capture", "TCP", "info",
        ["Derived from SYN→SYN-ACK vs SYN-ACK→ACK timing"],
        {"client": "If SYN-ACK→ACK is tiny, the capture was taken close to the client.",
         "server": "If SYN→SYN-ACK is tiny, the capture was taken close to the server.",
         "network": "Knowing where you captured is essential for interpreting which side of the path lost a packet.",
         "application": "N/A", "security": "N/A"},
        ["Keep the capture location in mind when interpreting retransmissions"], ["Capture at both ends for hard problems"], "tcp.flags.syn==1"),
    # ============================================================= IP/L3 ===
    "ip_ttl_anomaly": K(
        "Unusual IP TTL values", "Network", "IP", "low",
        ["Traffic from an unexpected OS or through more hops than usual (routing change)",
         "Spoofed packets or a device in the path generating packets on behalf of a host",
         "Link-local control protocols (OSPF, VRRP, HSRP) sent with TTL != 1 — misconfiguration or spoofing"],
        {"client": "TTL indicates hop distance (initial 64 Linux/macOS, 128 Windows, 255 network gear).",
         "server": "A server whose TTL suddenly changes may now be reached via a different path.",
         "network": "Different TTLs from the same source IP suggest multiple devices answering for it (LB, firewall, spoofing).",
         "application": "N/A", "security": "Chris Greer's 'Weird TTLs' button (ttl 30–50) highlights traffic from unusual OS/hop counts — a threat-hunting lead."},
        ["Compare TTL against the expected initial TTL and hop count", "Check for multiple devices answering for the same IP"],
        ["Baseline TTLs of critical servers", "Set GTSM (TTL security) on routing adjacencies"], "ip.ttl < 50 && ip.ttl > 30"),
    "ip_checksum_errors": K(
        "IP header checksum errors", "Network", "IP", "low",
        ["Checksum offload on the capturing host (packets captured before the NIC fills the checksum) — most common, harmless",
         "Real corruption from faulty NIC, memory or cabling"],
        {"client": "If captured on the sending host, almost certainly offload.", "server": "Same.",
         "network": "If seen on a TAP/SPAN, investigate the device that transmitted them.", "application": "Corrupted packets are dropped by the receiver → retransmissions.",
         "security": "Crafted packets with bad checksums can be used for IDS evasion."},
        ["Check whether the capture was taken on a sender with TX checksum offload"], ["Capture on a TAP when validating checksums"],
        "ip.checksum.status == \"Bad\""),
    "ip_fragmentation": K(
        "IP fragmentation", "Network", "IP", "low",
        ["Packets larger than the path MTU without DF bit (common with UDP: DNS/EDNS0, IPsec, SNMP)",
         "Tunnels reducing MTU"],
        {"client": "Loss of any fragment loses the whole datagram.", "server": "Reassembly consumes resources.",
         "network": "Fragments often dropped by firewalls; causes silent failures for large DNS responses.",
         "application": "Large UDP messages fail intermittently.", "security": "Fragment attacks (overlap, tiny fragments) are used for evasion."},
        ["Identify the MTU bottleneck", "Reduce payload size (EDNS0 buffer 1232) or clamp MSS"],
        ["Standardize MTU across the path; use PMTUD with ICMP allowed"], "ip.flags.mf == 1 || ip.frag_offset > 0"),
    # =============================================================== ICMP ===
    "icmp_unreachable": K(
        "ICMP destination unreachable", "Network", "ICMP", "medium",
        ["Network unreachable: no route on a router (routing hole)", "Host unreachable: ARP/ND failure on the last hop — host down",
         "Port unreachable: UDP service not listening", "Protocol unreachable: protocol not supported on host"],
        {"client": "The client gets an immediate error for the flow referenced in the ICMP payload.",
         "server": "Port unreachable from a server means the UDP service is down.",
         "network": "The source IP of the ICMP identifies the router/host reporting the failure — that's where to look.",
         "application": "Failures are fast (good) but indicate an outage or misconfiguration.",
         "security": "Bursts of port unreachables can indicate UDP port scanning."},
        ["Log into the reporting device (ICMP source) and check its routing table / ARP table",
         "For port unreachable: check the service on the destination host"],
        ["Monitor routing tables for missing prefixes", "Keep ICMP unreachables enabled internally for fast failure"], "icmp.type == 3"),
    "icmp_admin_prohibited": K(
        "ICMP administratively prohibited (firewall/ACL reject)", "Security", "ICMP", "high",
        ["An ACL, firewall rule or security policy explicitly rejects the traffic"],
        {"client": "Connection fails immediately.", "server": "Server never sees the request.",
         "network": "The ICMP source address is the filtering device.", "application": "Feature/API unavailable due to policy.",
         "security": "Expected if policy is correct; otherwise a rule change broke legitimate traffic."},
        ["Find the rule on the reporting device that matches the original 5-tuple (embedded in the ICMP payload)",
         "Review recent firewall change tickets"], ["Document application flows and validate firewall rules against them"],
        "icmp.type == 3 && icmp.code in {9 10 13}"),
    "icmp_frag_needed": K(
        "ICMP fragmentation needed / packet too big (PMTUD)", "Network", "ICMP", "medium",
        ["Path contains a lower-MTU link (tunnel, PPPoE, VPN) and DF-bit packets are too large",
         "MSS clamping missing on the tunnel"],
        {"client": "If these ICMPs are blocked anywhere, large packets vanish: the 'PMTUD black hole' — handshakes work, big transfers hang.",
         "server": "Servers must honor the ICMP and reduce segment size.", "network": "The next-hop MTU value in the ICMP tells you the bottleneck MTU.",
         "application": "Symptoms: login page loads but large pages/file transfers stall.", "security": "Blocking all ICMP breaks PMTUD — permit type 3 code 4 / ICMPv6 type 2."},
        ["Clamp TCP MSS on the tunnel interface", "Permit ICMP type 3 code 4 (and ICMPv6 Packet Too Big) through firewalls"],
        ["Align MTU across the path", "Consider PLPMTUD (RFC 4821/8899) on hosts"], "icmp.type == 3 && icmp.code == 4 || icmpv6.type == 2"),
    "icmp_ttl_exceeded": K(
        "ICMP time exceeded (TTL expired in transit)", "Routing", "ICMP", "medium",
        ["Routing loop between two or more routers (TTL decrements to zero)", "traceroute activity (benign)",
         "Very low initial TTL on the source"],
        {"client": "Traffic to the looped destination fails.", "server": "N/A",
         "network": "Repeated time-exceeded from the same routers for the same destination indicates a loop; the reporting routers are in it.",
         "routing": "Loops appear transiently during convergence or persistently with static route / redistribution mistakes.",
         "application": "Destination unreachable.", "security": "traceroute from unknown hosts is reconnaissance."},
        ["Traceroute to the destination and look for repeating hops", "Check routing tables of the reporting routers for the prefix",
         "Look for mutual redistribution or conflicting static routes"],
        ["Use route tags/filters with mutual redistribution", "Tune convergence (BFD, SPF throttling)"], "icmp.type == 11"),
    "icmp_redirect": K(
        "ICMP redirects", "Routing", "ICMP", "low",
        ["Host is using a suboptimal default gateway; router tells it to use another next hop on the same subnet"],
        {"client": "Traffic takes an extra hop until redirected.", "server": "N/A", "network": "Indicates asymmetric or suboptimal first-hop design.",
         "routing": "Consider FHRP design and correct gateway assignment.", "application": "N/A",
         "security": "Forged redirects are a MITM technique; hosts should ignore them."},
        ["Fix the host's default gateway / static routes"], ["Disable ICMP redirects on routers and hosts (no ip redirects)"], "icmp.type == 5"),
    "icmp_large_ping": K(
        "Large ICMP echo payloads", "Security", "ICMP", "low",
        ["MTU testing (ping -s / -l)", "ICMP tunneling / data exfiltration"],
        {"client": "N/A", "server": "N/A", "network": "Legit for PMTU testing.", "application": "N/A",
         "security": "Chris Greer's 'Large Pings' filter: ICMP with ip.len > 100 is a classic covert-channel indicator."},
        ["Inspect the ICMP payload for non-pattern data"], ["Limit ICMP payload size at the perimeter"], "(icmp || icmpv6) && ip.len > 100"),
    "icmp_recon": K(
        "ICMP reconnaissance (timestamp / info / mask requests)", "Security", "ICMP", "medium",
        ["OS fingerprinting tools (nmap -O) use unusual ICMP types"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "application": "N/A",
         "security": "Chris Greer's 'OS Fingerprint' filter (icmp.type 13/15/17). Treat as reconnaissance."},
        ["Identify the source host and its purpose"], ["Block ICMP timestamp/info/mask at the edge"], "icmp.type == 13 || icmp.type == 15 || icmp.type == 17"),
    # ================================================================ DNS ===
    "dns_no_response": K(
        "DNS queries without response", "Application", "DNS", "high",
        ["Resolver unreachable / down, firewall blocking UDP 53, or resolver overloaded",
         "Response too large and fragments dropped (EDNS0)", "Upstream forwarders timing out"],
        {"client": "Resolver timeout is typically 1–5 s per attempt; applications stall before even opening a connection.",
         "server": "The DNS server may be overloaded, rate-limiting or not listening on this interface.",
         "network": "Check the path to the resolver and UDP/53 policies (and TCP/53 for truncated answers).",
         "application": "Everything 'feels slow' or fails — name resolution precedes every connection.",
         "security": "Queries to unknown resolvers that go unanswered may be blocked DNS tunneling attempts."},
        ["Test the resolver directly (dig @server name)", "Check resolver health and forwarders", "Check firewalls for UDP/TCP 53"],
        ["Configure at least two resolvers in different failure domains", "Monitor resolver latency and SERVFAIL rates"],
        "dns.flags.response == 0 && !dns.response_in"),
    "dns_slow": K(
        "Slow DNS responses", "Application", "DNS", "medium",
        ["Resolver cache miss requiring recursive resolution to distant authoritative servers",
         "Overloaded resolver or slow upstream forwarder", "Network latency/loss to the resolver"],
        {"client": "Every new hostname adds this delay before the TCP handshake.", "server": "Resolver CPU/recursion capacity may be exhausted.",
         "network": "Compare DNS time with TCP iRTT to the same resolver to separate network from resolver delay.",
         "application": "Page loads with many third-party domains multiply the delay.", "security": "None."},
        ["Check resolver cache hit ratio and forwarder latency", "Place resolvers close to clients"],
        ["Chris Greer's 'Slow DNS' button flags dns.time > 0.05 s; alert on resolver p95 latency"], "dns.time > 0.05"),
    "dns_nxdomain": K(
        "DNS NXDOMAIN (name does not exist)", "Application", "DNS", "low",
        ["Typo or stale hostname in configuration", "Search-domain suffix appending (normal noise)",
         "Deleted DNS record", "Malware DGA producing random domains"],
        {"client": "Client cannot connect to the intended service.", "server": "Authoritative zone lacks the record.",
         "network": "Not a network problem.", "application": "Misconfigured endpoints/URLs.",
         "security": "High NXDOMAIN volume with random-looking names is a DGA (botnet) indicator."},
        ["Verify the queried name and the zone contents", "Fix application/host configuration"],
        ["Monitor NXDOMAIN rate per client"], "dns.flags.rcode == 3"),
    "dns_servfail": K(
        "DNS SERVFAIL", "Application", "DNS", "high",
        ["Resolver could not reach authoritative servers", "DNSSEC validation failure (expired signatures, bad DS)",
         "Lame delegation / broken forwarder"],
        {"client": "Resolution fails; applications cannot connect.", "server": "Check resolver logs for the upstream error.",
         "network": "Resolver's upstream connectivity (UDP/TCP 53) may be blocked.", "application": "Service unreachable by name.",
         "security": "DNSSEC failures can indicate tampering or operational key-rollover errors."},
        ["Query the authoritative servers directly", "Check DNSSEC chain with delv/dnsviz", "Check resolver upstream connectivity"],
        ["Monitor SERVFAIL rate; automate DNSSEC key rollovers"], "dns.flags.rcode == 2"),
    "dns_refused": K(
        "DNS REFUSED", "Application", "DNS", "high",
        ["Resolver ACL does not allow this client (recursion disabled for that subnet)", "Querying an authoritative-only server for recursion"],
        {"client": "Client is pointing at the wrong DNS server.", "server": "Resolver policy rejects the client.",
         "network": "N/A", "application": "Resolution fails.", "security": "Proper behavior for open-resolver hardening."},
        ["Point the client at an authorized resolver (check DHCP option 6)", "Adjust resolver allow-recursion ACL"],
        ["Keep DHCP-provided DNS servers consistent with resolver ACLs"], "dns.flags.rcode == 5"),
    "dns_truncated": K(
        "Truncated DNS responses (TC bit)", "Application", "DNS", "low",
        ["Answer larger than UDP buffer; client must retry over TCP/53"],
        {"client": "Adds a TCP handshake round trip.", "server": "N/A", "network": "If TCP/53 is blocked, resolution fails for large answers.",
         "application": "Intermittent failures for records with many answers (DNSSEC, TXT).", "security": "N/A"},
        ["Ensure TCP/53 is permitted to resolvers"], ["Use EDNS0 buffer size 1232 (DNS Flag Day 2020)"], "dns.flags.truncated == 1"),
    "dns_high_answer_count": K(
        "High DNS answer count", "Security", "DNS", "info",
        ["CDN/load balancing records", "Fast-flux networks rotating many IPs"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "application": "N/A",
         "security": "Chris Greer's 'High DNS Count' colouring rule (dns.count.answers > 5) — check for fast-flux."},
        ["Review the domain's reputation"], ["Feed DNS logs to threat intel"], "dns.count.answers > 5"),
    "dns_suspicious_names": K(
        "Suspicious DNS names (possible tunneling / DGA)", "Security", "DNS", "medium",
        ["Very long or high-entropy labels used to encode data (DNS tunneling: iodine, dnscat2)", "Domain generation algorithms"],
        {"client": "The querying host may be compromised.", "server": "N/A", "network": "DNS is often allowed outbound, making it a covert channel.",
         "application": "N/A", "security": "Investigate the host; block the parent domain; look for high query volume to one domain."},
        ["Isolate and investigate the querying host", "Block the domain at the resolver (RPZ)"],
        ["Force all DNS through monitored resolvers; deploy DNS security analytics"], "len(dns.qry.name) > 50"),
    "dns_non_local_resolver": K(
        "DNS to non-local (external) resolvers", "Security", "DNS", "low",
        ["Hosts hard-coded to public resolvers (8.8.8.8, 1.1.1.1)", "Malware bypassing corporate DNS"],
        {"client": "Bypasses internal names/split-horizon and security filtering.", "server": "N/A",
         "network": "Egress policy allows direct DNS.", "application": "Internal names fail to resolve.",
         "security": "Chris Greer's 'Non Local DNS' filter — policy bypass and possible exfiltration channel."},
        ["Identify the hosts and why they bypass internal DNS"], ["Block outbound 53/853 except from corporate resolvers"],
        "dns && !(ip.dst == 10.0.0.0/8 || ip.dst == 172.16.0.0/12 || ip.dst == 192.168.0.0/16)"),
    # =============================================================== DHCP ===
    "dhcp_no_offer": K(
        "DHCP DISCOVER without OFFER", "Application", "DHCP", "high",
        ["No DHCP server on the segment and no relay (ip helper-address) configured on the VLAN interface",
         "DHCP scope exhausted", "DHCP snooping dropping (untrusted port) or server unreachable from the relay",
         "Client in the wrong VLAN"],
        {"client": "Client retries with backoff, then self-assigns an APIPA 169.254.x.x address — no connectivity.",
         "server": "Server may never receive the DISCOVER (relay issue) or have no free leases.",
         "network": "Check the SVI/router interface for ip helper-address and DHCP snooping trust configuration.",
         "application": "Nothing works on that host.", "security": "DHCP snooping misconfiguration blocks legitimate servers."},
        ["Verify helper-address on the client VLAN gateway", "Check the scope's free leases", "Check DHCP snooping trusted ports",
         "Check the switchport VLAN assignment"],
        ["Monitor scope utilization (alert > 80%)", "Deploy redundant DHCP (failover)"], "dhcp.option.dhcp == 1"),
    "dhcp_no_ack": K(
        "DHCP REQUEST without ACK", "Application", "DHCP", "high",
        ["Server received the request but did not answer (address conflict, database issue)", "Relay/server path failure after the offer"],
        {"client": "Client restarts the DORA process; delays of seconds to minutes.", "server": "Check the server logs for this transaction ID.",
         "network": "Verify return path from server to relay.", "application": "Host lacks connectivity.", "security": "N/A"},
        ["Check DHCP server logs for the xid/MAC"], ["Deploy DHCP failover"], "dhcp.option.dhcp == 3"),
    "dhcp_nak": K(
        "DHCP NAK", "Application", "DHCP", "medium",
        ["Client requested an address from a different subnet (moved VLAN/network)", "Lease no longer valid on the server",
         "Two authoritative servers disagreeing"],
        {"client": "Client must restart DORA — usually a short delay.", "server": "The server rejected the requested IP.",
         "network": "Roaming between VLANs triggers NAKs.", "application": "Short connectivity loss.", "security": "Rogue servers can NAK to disrupt clients."},
        ["Check the NAK message option and server logs", "Check for multiple authoritative servers"],
        ["Ensure only one authoritative server per scope"], "dhcp.option.dhcp == 6"),
    "dhcp_decline": K(
        "DHCP DECLINE (IP address conflict)", "Network", "DHCP", "high",
        ["The offered IP is already in use (static IP inside the DHCP scope, or stale lease)"],
        {"client": "Client detected the conflict via ARP probe and refused the address.", "server": "Server marks the address bad.",
         "network": "A static device is using an address inside the pool.", "application": "Delay acquiring an address.",
         "security": "Could be an attacker squatting on addresses."},
        ["Find the device using the conflicting IP (ARP table)", "Exclude static addresses from the scope"],
        ["Use DHCP reservations and IPAM"], "dhcp.option.dhcp == 4"),
    "dhcp_multiple_servers": K(
        "Multiple DHCP servers answering (possible rogue DHCP)", "Security", "DHCP", "critical",
        ["Unauthorized DHCP server (home router plugged in, misconfigured VM)", "Legitimate failover pair both answering"],
        {"client": "Client may accept a lease with the wrong gateway/DNS — traffic diverted or broken.",
         "server": "Legitimate server loses clients.", "network": "Clients get inconsistent addressing.",
         "application": "Intermittent failures depending on which offer wins.",
         "security": "Rogue DHCP is a MITM technique: attacker sets itself as gateway/DNS."},
        ["Locate the rogue server by MAC (switch MAC table)", "Shut the port"],
        ["Enable DHCP snooping with trusted uplinks only", "Enable DHCP snooping on all access VLANs"], "dhcp.option.dhcp == 2"),
    "dhcp_slow": K(
        "Slow DHCP transaction", "Application", "DHCP", "low",
        ["Server/relay latency, server doing ping-check before offering, STP port not in forwarding (no portfast)"],
        {"client": "Boot/network join takes seconds longer.", "server": "Ping-check adds ~500 ms by design.",
         "network": "STP listening/learning delays DHCP up to 30 s without portfast.", "application": "Delayed login scripts.", "security": "N/A"},
        ["Enable portfast/edge on access ports"], ["Monitor DORA times"], "dhcp"),
    "dhcp_apipa": K(
        "APIPA / link-local addresses in use", "Network", "DHCP", "medium",
        ["DHCP failed and hosts self-assigned 169.254.0.0/16"],
        {"client": "Host has no routable address.", "server": "N/A", "network": "DHCP/relay failure on that segment.", "application": "No connectivity.", "security": "N/A"},
        ["Troubleshoot DHCP on that segment"], ["Monitor for 169.254/16 sources"], "ip.src == 169.254.0.0/16"),
    # =============================================================== HTTP ===
    "http_server_errors": K(
        "HTTP 5xx server errors", "Application", "HTTP", "high",
        ["Application exception/crash (500)", "Upstream/backend failure behind a proxy or LB (502/503/504)", "Overload or maintenance (503)"],
        {"client": "User sees an error page.", "server": "Check application and proxy logs at the timestamp.",
         "network": "504 often means the proxy could not reach the backend in time — check the backend network path.",
         "application": "Bug or dependency failure.", "security": "Error pages may leak stack traces."},
        ["Correlate with server logs for the URI", "Check backend health behind the proxy"], ["APM + error-rate SLO alerting"],
        "http.response.code >= 500"),
    "http_client_errors": K(
        "HTTP 4xx client errors", "Application", "HTTP", "low",
        ["Broken links (404)", "Authentication/authorization failures (401/403)", "Rate limiting (429)"],
        {"client": "Client requested something it can't have.", "server": "Server working as designed.", "network": "N/A",
         "application": "Configuration/link errors.", "security": "Many 401/403/404 from one source = brute force or directory enumeration (gobuster)."},
        ["Review the requested URIs"], ["Monitor 4xx rate per client"], "http.response.code >= 400 && http.response.code < 500"),
    "http_slow_response": K(
        "Slow HTTP response (http.time > 2 s)", "Application", "HTTP", "high",
        ["Server-side processing delay (see TCP response time analysis)"],
        {"client": "Waiting on the server.", "server": "Server think time is the bottleneck.", "network": "Check for retransmissions during the wait to rule out the network.",
         "application": "Slow endpoint.", "security": "N/A"},
        ["Trace the URI in the server's APM"], ["Chris Greer's 'Slow HTTP' button: http.time > 2"], "http.time > 2"),
    "http_old_version": K(
        "HTTP/1.0 requests", "Security", "HTTP", "low",
        ["Legacy clients, scripts or scanners"],
        {"client": "No persistent connections by default → extra handshakes.", "server": "N/A", "network": "N/A", "application": "Inefficient.",
         "security": "Chris Greer's 'Weird HTTP Version' filter — many attack tools use HTTP/1.0."},
        ["Identify the client software"], ["Use HTTP/1.1+ or HTTP/2"], "http.request.version == \"HTTP/1.0\""),
    "http_no_user_agent": K(
        "HTTP requests without User-Agent", "Security", "HTTP", "low",
        ["Scripts, IoT devices, malware"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "application": "N/A", "security": "Chris Greer's 'No User Agent' filter — investigate automated clients."},
        ["Identify the process generating the request"], ["Proxy policy for unidentified clients"], "http.request && !http.user_agent"),
    "http_suspicious_user_agent": K(
        "Suspicious HTTP User-Agent", "Security", "HTTP", "high",
        ["Scanning/attack tools: nmap, gobuster, sqlmap, nikto, dirbuster, masscan", "Outdated 'Mozilla/4.0' strings used by malware"],
        {"client": "The source may be an attacker or a compromised host.", "server": "The target is being probed.", "network": "N/A",
         "application": "Expect 404 floods and injection attempts.", "security": "Chris Greer's 'Gobuster', 'UserAgentNmap', 'Old Mozilla' filters."},
        ["Block/investigate the source", "Review server logs for successful responses to the tool"], ["WAF with bot/scanner detection"],
        "http.user_agent matches \"(?i)(nmap|gobuster|sqlmap|nikto|dirbuster|masscan|Mozilla/4.0)\""),
    "http_file_download": K(
        "Executable / archive file transfer over HTTP", "Security", "HTTP", "medium",
        ["Software updates", "Malware stage-2 download"],
        {"client": "Host downloaded a binary in cleartext.", "server": "N/A", "network": "N/A", "application": "N/A",
         "security": "Chris Greer's 'HTTP File Transfers' / 'JPG EXE ZIP PDF BIN' filters. Verify hash reputation."},
        ["Export the object (File → Export Objects → HTTP) and check its hash"], ["Enforce HTTPS and download scanning"],
        "http.request.uri matches \"\\\\.(exe|zip|bin|ps1|dll|msi|tar|php)\""),
    "http_cleartext_credentials": K(
        "Credentials sent in cleartext", "Security", "HTTP", "critical",
        ["HTTP Basic auth or login forms over plain HTTP", "Legacy protocols (FTP/Telnet/POP3)"],
        {"client": "Password exposed to anyone on the path.", "server": "Server accepts insecure authentication.", "network": "Any SPAN/TAP or MITM reveals it.",
         "application": "Must move to TLS.", "security": "Chris Greer's 'Password' filter (frame matches \"(?i)pass\"). Rotate exposed credentials."},
        ["Rotate the exposed credentials", "Enable TLS/redirect HTTP→HTTPS"], ["HSTS, disable Basic over HTTP, disable cleartext protocols"],
        "http.authorization || frame matches \"(?i)pass\""),
    # ================================================================ TLS ===
    "tls_old_version": K(
        "Deprecated SSL/TLS version (SSLv3 / TLS 1.0 / 1.1)", "Security", "TLS", "medium",
        ["Legacy client or server libraries", "Server configured to allow old protocols"],
        {"client": "Vulnerable to downgrade attacks (POODLE, BEAST).", "server": "Fails compliance (PCI DSS).", "network": "N/A",
         "application": "Modern clients may refuse to connect.", "security": "Chris Greer's 'Old TLS' filter (tls.handshake.version in {0x0300 0x0301 0x0302})."},
        ["Upgrade the client/server TLS library", "Disable TLS < 1.2 on servers"], ["Enforce TLS 1.2+ (prefer 1.3) organization-wide"],
        "tls.handshake.version in {0x0300 0x0301 0x0302}"),
    "tls_weak_cipher": K(
        "Weak cipher suites offered or selected", "Security", "TLS", "medium",
        ["RC4, 3DES, DES, EXPORT or NULL cipher suites enabled"],
        {"client": "Offering weak ciphers enables downgrade.", "server": "Selecting a weak cipher is a direct vulnerability.", "network": "N/A",
         "application": "N/A", "security": "Sweet32 / RC4 biases / FREAK / Logjam."},
        ["Remove weak suites from client and server configuration"], ["Use Mozilla 'intermediate' or 'modern' TLS profile"],
        "tls.handshake.ciphersuite in {0x0004 0x0005 0x000a}"),
    "tls_alert": K(
        "TLS handshake alert", "Application", "TLS", "high",
        ["handshake_failure: no common cipher/protocol", "unknown_ca / bad_certificate: client does not trust the server certificate (missing intermediate, self-signed, TLS inspection)",
         "certificate_expired", "protocol_version: version not supported", "unrecognized_name: SNI mismatch"],
        {"client": "Connection fails before any application data.", "server": "Check certificate chain and enabled protocols/ciphers.",
         "network": "TLS-inspecting proxies re-sign certificates — clients without the proxy CA send unknown_ca.",
         "application": "Service unreachable over HTTPS.", "security": "Unexpected certificate issuers may indicate interception."},
        ["Test with openssl s_client -connect host:443 -servername name", "Verify the full chain and expiry", "Check protocol/cipher overlap"],
        ["Automate certificate renewal and monitoring (expiry alerts)"], "tls.alert_message"),
    "tls_handshake_failure": K(
        "TLS ClientHello without ServerHello", "Application", "TLS", "high",
        ["Server/middlebox rejected the handshake (RST or silent drop)", "SNI-based filtering by a firewall/proxy", "Protocol/cipher mismatch"],
        {"client": "Client times out or gets reset after sending ClientHello.", "server": "Server may not support the requested SNI/protocol.",
         "network": "Next-gen firewalls block by SNI with RST — check the RST TTL.", "application": "HTTPS failure.",
         "security": "Could be URL filtering doing its job."},
        ["Check which device sent the RST", "Check firewall URL/SNI policies"], ["Monitor TLS handshake success rates"],
        "tls.handshake.type == 1"),
    "tls_known_bad_ja3": K(
        "Known-malicious TLS client fingerprint (JA3)", "Security", "TLS", "critical",
        ["Malware family with a distinctive TLS stack (Trickbot, Cobalt Strike, Metasploit)"],
        {"client": "Host likely compromised.", "server": "Likely command-and-control server.", "network": "Block the destination.",
         "application": "N/A", "security": "Chris Greer's ThreatHunt profile flags Trickbot's JA3 (6734f37431670b3ab4292b8f60f29984)."},
        ["Isolate the host, run IR procedures", "Block the destination IP/SNI"], ["Deploy JA3/JA4 detection in NDR/IDS"], "tls.handshake.ja3"),
    "tls_missing_sni": K(
        "TLS ClientHello without SNI", "Security", "TLS", "info",
        ["Connecting by IP address", "Legacy clients", "Malware"],
        {"client": "N/A", "server": "Server may present the default certificate.", "network": "N/A", "application": "Possible certificate mismatch.",
         "security": "Direct-to-IP TLS is a weak C2 indicator."},
        ["Identify the client"], ["N/A"], "tls.handshake.type == 1 && !tls.handshake.extensions_server_name"),
    "http2_goaway": K(
        "HTTP/2 GOAWAY with error", "Application", "HTTP2", "high",
        ["PROTOCOL_ERROR / COMPRESSION_ERROR: client and server (or a proxy between them) disagree on framing or HPACK state",
         "ENHANCE_YOUR_CALM: the peer considers this client abusive (too many streams / resets — rapid-reset protection)",
         "INTERNAL_ERROR: server/proxy crashed or restarted mid-connection", "Graceful shutdown during deploys uses NO_ERROR (not flagged)"],
        {"client": "All streams above 'last stream' must be retried on a new connection.",
         "server": "Check server/proxy logs at this time; GOAWAY with debug data often names the reason.",
         "network": "Middleboxes that rewrite or inspect HTTP/2 can corrupt HPACK state.",
         "application": "Requests fail or are retried, adding latency.",
         "security": "ENHANCE_YOUR_CALM is typical of DoS protection (e.g. HTTP/2 rapid reset, CVE-2023-44487)."},
        ["Read the GOAWAY error and debug text", "Correlate with server/proxy logs and restarts", "Test the same request bypassing the proxy/load balancer"],
        ["Keep HTTP/2 stacks patched", "Tune concurrent-stream limits consistently across proxy tiers"], "http2.goaway.error != 0"),
    "http2_rst_stream": K(
        "HTTP/2 streams reset", "Application", "HTTP2", "medium",
        ["REFUSED_STREAM: server over its concurrency limit — request never processed, safe to retry",
         "INTERNAL_ERROR: server failure while handling the request", "FLOW_CONTROL_ERROR: peer violated window limits (stack bug)",
         "PROTOCOL_ERROR: malformed request/headers"],
        {"client": "Individual requests fail while the connection stays up.",
         "server": "Look for overload (REFUSED_STREAM) or exceptions (INTERNAL_ERROR).",
         "network": "Rarely network-related.", "application": "Partial page loads, failed API calls.",
         "security": "Floods of client resets are the HTTP/2 rapid-reset attack pattern."},
        ["Group resets by error code and endpoint", "Check server concurrency limits and errors"],
        ["Monitor RST_STREAM rates per error code"], "http2.rst_stream.error != 0"),
    # ================================================================ BGP ===
    "bgp_notification": K(
        "BGP NOTIFICATION (session torn down)", "Routing", "BGP", "critical",
        ["Hold Timer Expired: keepalives lost (link congestion, CPU spike, MTU issue on large UPDATEs)",
         "OPEN Message Error: Bad Peer AS / unacceptable hold time / bad BGP identifier — configuration mismatch",
         "Cease/Max-prefix: peer sent more prefixes than allowed", "Cease/Admin shutdown or reset by operator",
         "UPDATE Message Error: malformed attributes"],
        {"client": "End users lose reachability to prefixes learned over this session until reconvergence.",
         "server": "Services behind the affected prefixes become unreachable or take a suboptimal path.",
         "network": "Check the TCP session: retransmissions/zero window before the NOTIFICATION point to transport problems.",
         "routing": "All routes from the peer are withdrawn; best-path recalculation and churn ripple to other peers.",
         "application": "Outages or latency shifts while BGP reconverges (seconds to minutes).",
         "security": "Unexpected sessions or AS changes may indicate hijack attempts; use TCP-AO/MD5 and RPKI."},
        ["Read the error code/subcode to identify the side at fault", "For Hold Timer Expired: look at TCP retransmissions and interface drops before the event",
         "For OPEN errors: compare neighbor remote-as, router-id and timers", "For max-prefix: verify peer's advertisements and your limits"],
        ["Enable BFD for fast, reliable failure detection", "Enable graceful restart / long-lived GR", "Use max-prefix with warning thresholds",
         "Protect control-plane (CoPP) so keepalives aren't dropped under load"], "bgp.type == 3"),
    "bgp_session_flap": K(
        "BGP session re-establishment / flap", "Routing", "BGP", "high",
        ["Unstable underlying link, keepalive loss, repeated configuration resets"],
        {"client": "Intermittent reachability.", "server": "N/A", "network": "Underlying link errors.",
         "routing": "Route dampening may suppress prefixes after repeated flaps.", "application": "Intermittent outages.", "security": "N/A"},
        ["Check interface errors and BGP logs"], ["BFD, dampening policy review"], "bgp.type == 1"),
    "bgp_withdrawals": K(
        "BGP route withdrawals", "Routing", "BGP", "medium",
        ["Upstream link/peer failure, policy change, or prefix de-aggregation"],
        {"client": "Destinations in withdrawn prefixes may become unreachable.", "server": "N/A", "network": "N/A",
         "routing": "Large withdrawal bursts indicate a peer or upstream failure.", "application": "Possible outage.", "security": "Unexpected withdrawals may indicate leaks/hijacks elsewhere."},
        ["Identify withdrawn prefixes and their origin"], ["Monitor BGP with BMP/route analytics"], "bgp.update.withdrawn_routes"),
    "bgp_connect_fail": K(
        "BGP TCP session cannot be established (TCP/179)", "Routing", "BGP", "critical",
        ["Neighbor address wrong or unreachable (no route to loopback, missing update-source/ebgp-multihop)",
         "ACL/firewall blocking TCP 179", "Peer not configured (RST)", "TTL security (GTSM) mismatch"],
        {"client": "N/A", "server": "N/A", "network": "Verify IP reachability between peering addresses.",
         "routing": "Session stays in Active/Connect; no routes exchanged.", "application": "Missing routes.", "security": "N/A"},
        ["Ping the neighbor from the correct source", "Check ACLs for TCP/179", "Verify neighbor configuration on both sides"],
        ["Use loopbacks with update-source and IGP reachability"], "tcp.port == 179 && (tcp.flags.reset==1 || tcp.analysis.retransmission)"),
    # =============================================================== OSPF ===
    "ospf_hello_mismatch": K(
        "OSPF hello/dead interval mismatch", "Routing", "OSPF", "critical",
        ["Different 'ip ospf hello-interval'/'dead-interval' configured on neighbors", "Different network types (broadcast vs point-to-point default timers)"],
        {"client": "Hosts behind these routers may lose alternative paths.", "server": "N/A",
         "network": "Neighbors ignore each other's hellos — adjacency never forms.",
         "routing": "No adjacency → no LSDB sync → missing routes or suboptimal paths.", "application": "Reachability issues.", "security": "N/A"},
        ["Align hello/dead intervals on both interfaces", "Align ip ospf network type"], ["Use configuration templates and compliance checks"], "ospf.msg.hello"),
    "ospf_area_mismatch": K(
        "OSPF area mismatch", "Routing", "OSPF", "critical",
        ["Interfaces on the same link placed in different areas"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Adjacency cannot form.", "application": "Missing routes.", "security": "N/A"},
        ["Put both interfaces in the same area"], ["Standardize area design documentation"], "ospf.area_id"),
    "ospf_mask_mismatch": K(
        "OSPF network mask mismatch", "Routing", "OSPF", "high",
        ["Different subnet masks on a broadcast/NBMA link"],
        {"client": "N/A", "server": "N/A", "network": "Addressing inconsistency.", "routing": "Adjacency cannot form on broadcast networks.", "application": "N/A", "security": "N/A"},
        ["Correct the interface mask"], ["IPAM validation"], "ospf.hello.network_mask"),
    "ospf_auth_mismatch": K(
        "OSPF authentication type mismatch", "Routing", "OSPF", "critical",
        ["Authentication enabled on one side only or with different types/keys"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Hellos are dropped; no adjacency.", "application": "N/A",
         "security": "Authentication should be consistent (prefer SHA HMAC over MD5/plain)."},
        ["Configure identical authentication on both neighbors"], ["Use OSPF HMAC-SHA authentication area-wide"], "ospf.auth.type"),
    "ospf_mtu_mismatch": K(
        "OSPF MTU mismatch in DB Description", "Routing", "OSPF", "critical",
        ["Interface MTU differs between neighbors"],
        {"client": "N/A", "server": "N/A", "network": "Also a data-plane risk: large packets may be dropped on the smaller-MTU side.",
         "routing": "Neighbors stuck in EXSTART/EXCHANGE, DBD packets retransmitted forever — classic OSPF issue.", "application": "Routes missing.", "security": "N/A"},
        ["Match interface MTU on both sides (preferred) or use 'ip ospf mtu-ignore'"], ["Standardize MTU per link type"], "ospf.db.interface_mtu"),
    "ospf_exstart_stuck": K(
        "OSPF DBD retransmissions (neighbor stuck in EXSTART/EXCHANGE)", "Routing", "OSPF", "high",
        ["MTU mismatch", "Duplicate router IDs", "Unicast reachability issue between neighbors"],
        {"client": "N/A", "server": "N/A", "network": "DBDs lost or rejected.", "routing": "LSDB never synchronizes.", "application": "N/A", "security": "N/A"},
        ["Check MTU and router IDs"], ["N/A"], "ospf.msg.dbdesc"),
    "ospf_duplicate_rid": K(
        "Duplicate OSPF router ID", "Routing", "OSPF", "critical",
        ["Two routers share a router ID (cloned configs, loopback copied)"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "LSAs overwrite each other, causing flapping routes and SPF churn.",
         "application": "Intermittent reachability.", "security": "A rogue router spoofing a RID can hijack routes."},
        ["Assign unique router IDs (router-id command)"], ["Derive RID from unique loopback; audit"], "ospf.srcrouter"),
    "ospf_one_way": K(
        "OSPF one-way adjacency (neighbor not listed in Hello)", "Routing", "OSPF", "high",
        ["Unidirectional link / multicast filtering", "ACL blocking 224.0.0.5/6 in one direction", "Hello parameters mismatched on the other side"],
        {"client": "N/A", "server": "N/A", "network": "Check multicast and layer-2 unidirectional faults (UDLD).",
         "routing": "Neighbor stuck in INIT state.", "application": "N/A", "security": "N/A"},
        ["Verify both routers receive each other's hellos"], ["Enable UDLD on fiber links"], "ospf.msg.hello"),
    "ospf_lsu_storm": K(
        "High OSPF LS Update volume (instability)", "Routing", "OSPF", "medium",
        ["Flapping link or neighbor causing repeated LSA flooding", "Redistribution churn"],
        {"client": "N/A", "server": "N/A", "network": "Flapping interface.", "routing": "Frequent SPF runs consume CPU and cause transient loops.",
         "application": "Micro-outages.", "security": "N/A"},
        ["Find the originating router of the changing LSAs"], ["SPF/LSA throttling, summarize areas, dampen interfaces"], "ospf.msg.lsupdate"),
    # ============================================================== EIGRP ===
    "eigrp_k_mismatch": K(
        "EIGRP K-value mismatch", "Routing", "EIGRP", "critical",
        ["'metric weights' configured differently on neighbors"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Neighbors refuse to peer ('K-value mismatch').", "application": "Missing routes.", "security": "N/A"},
        ["Align metric weights on all routers in the AS"], ["Leave default K-values unless there is a strong reason"], "eigrp"),
    "eigrp_as_mismatch": K(
        "EIGRP autonomous-system number mismatch", "Routing", "EIGRP", "critical",
        ["Neighbors configured with different AS numbers"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "No adjacency.", "application": "Missing routes.", "security": "N/A"},
        ["Use the same 'router eigrp <AS>' on both"], ["Standardize"], "eigrp.as"),
    "eigrp_goodbye": K(
        "EIGRP Goodbye (neighbor shutting down)", "Routing", "EIGRP", "high",
        ["Neighbor removed/reconfigured (network statement removed, passive-interface, reload)"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Adjacency dropped; routes via this neighbor withdrawn and queries sent.",
         "application": "Brief outage while DUAL converges.", "security": "N/A"},
        ["Check change logs on the neighbor"], ["Change control for routing changes"], "eigrp"),
    "eigrp_sia": K(
        "EIGRP Stuck-in-Active (SIA queries)", "Routing", "EIGRP", "critical",
        ["A queried neighbor did not reply in time: query scope too large, congested/lossy link, overloaded router CPU"],
        {"client": "N/A", "server": "N/A", "network": "Lossy links delay replies.",
         "routing": "The router resets the neighbor that failed to reply — large-scale route loss.",
         "application": "Outages across the EIGRP domain.", "security": "N/A"},
        ["Find which neighbor fails to reply", "Check that link for loss/CPU"], ["Limit query scope with summarization and stub routing"], "eigrp.opcode == 10 || eigrp.opcode == 11"),
    "eigrp_query_storm": K(
        "EIGRP query activity (routes going active)", "Routing", "EIGRP", "medium",
        ["A route was lost and no feasible successor exists — DUAL diffusing computation"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Many queries indicate topology instability and large query domains.",
         "application": "Convergence delay.", "security": "N/A"},
        ["Identify the lost prefixes"], ["Summarization and EIGRP stub on spokes"], "eigrp.opcode == 3"),
    "eigrp_retrans": K(
        "EIGRP reliable packet retransmissions", "Routing", "EIGRP", "high",
        ["Loss on the link between neighbors; unicast reachability issues; neighbor CPU overload"],
        {"client": "N/A", "server": "N/A", "network": "Link loss.", "routing": "After 16 retries the neighbor is reset ('retry limit exceeded').",
         "application": "Flaps.", "security": "N/A"},
        ["Check link errors between neighbors"], ["Fix the link; consider BFD"], "eigrp"),
    "eigrp_auth_mismatch": K(
        "EIGRP authentication mismatch", "Routing", "EIGRP", "critical",
        ["Authentication configured on one neighbor only / different keys"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Packets dropped; no adjacency.", "application": "N/A", "security": "Enable auth consistently."},
        ["Align key-chains"], ["Use SHA-256 EIGRP authentication (named mode)"], "eigrp"),
    "eigrp_unreachable_routes": K(
        "EIGRP routes advertised as unreachable (infinite delay)", "Routing", "EIGRP", "medium",
        ["Route withdrawn / poisoned — the prefix was lost"],
        {"client": "Hosts in the prefix may become unreachable.", "server": "N/A", "network": "N/A",
         "routing": "Indicates a topology change for these prefixes.", "application": "Possible outage.", "security": "N/A"},
        ["Find where the prefix originated and why it was lost"], ["Monitor route churn"], "eigrp"),
    # ================================================================ RIP ===
    "rip_version_mismatch": K(
        "RIP version mismatch (v1 and v2 on same segment)", "Routing", "RIP", "high",
        ["Routers configured with different 'version' settings"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Updates are ignored by the router expecting the other version — routes missing.",
         "application": "N/A", "security": "N/A"},
        ["Configure 'version 2' on all routers"], ["Migrate to OSPF/EIGRP for faster convergence"], "rip.version"),
    "rip_unreachable_routes": K(
        "RIP routes with metric 16 (unreachable / poisoned)", "Routing", "RIP", "medium",
        ["Route withdrawal via poison reverse / route poisoning after a link failure", "Network more than 15 hops away"],
        {"client": "Destinations in these networks are unreachable.", "server": "N/A", "network": "N/A",
         "routing": "RIP counts to infinity (16); convergence can take minutes (holddown 180 s).", "application": "Outage.", "security": "N/A"},
        ["Find the failed link/originator for the prefix"], ["Consider a link-state protocol"], "rip.metric == 16"),
    "rip_v1_in_use": K(
        "RIPv1 in use (classful, broadcast, no authentication)", "Routing", "RIP", "medium",
        ["Legacy configuration"],
        {"client": "N/A", "server": "N/A", "network": "Broadcast updates reach all hosts.", "routing": "Classful: no VLSM, discontiguous networks break.",
         "application": "N/A", "security": "Anyone can inject routes (no authentication)."},
        ["Upgrade to RIPv2 with authentication, or migrate to OSPF"], ["Retire RIPv1"], "rip.version == 1"),
    "rip_no_auth": K(
        "RIPv2 without authentication", "Security", "RIP", "low",
        ["Authentication not configured"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Route injection possible.", "application": "N/A", "security": "Enable MD5 authentication."},
        ["Configure key-chain authentication"], ["Passive-interface on user-facing interfaces"], "rip.version == 2"),
    "rip_update_gap": K(
        "Missed RIP periodic updates", "Routing", "RIP", "medium",
        ["Link loss, router CPU overload, or updates filtered"],
        {"client": "N/A", "server": "N/A", "network": "Loss on the link.", "routing": "Routes time out after 180 s without updates, then are flushed.",
         "application": "Intermittent outages.", "security": "N/A"},
        ["Check link errors and router CPU"], ["Monitor route timers"], "rip"),
    # ========================================================= HSRP / VRRP ===
    "fhrp_split_brain": K(
        "FHRP split brain (two active gateways)", "Routing", "FHRP", "critical",
        ["The routers cannot hear each other's hellos: layer-2 path between them broken (VLAN not trunked, STP blocking, port down)",
         "Authentication or group/VRID mismatch makes each router ignore the other",
         "ACL/CoPP dropping 224.0.0.2/224.0.0.102 (HSRP) or protocol 112 (VRRP)"],
        {"client": "Hosts' ARP entries for the virtual MAC flap between routers; traffic may be black-holed or asymmetric.",
         "server": "Return traffic may take the other gateway; stateful firewalls then drop it.",
         "network": "Both routers answer for the virtual IP/MAC — MAC flapping on switches.",
         "routing": "Both routers inject the connected subnet as active; asymmetric routing follows.",
         "application": "Intermittent timeouts and resets for hosts on this VLAN.",
         "security": "An attacker sending higher-priority hellos can take over the gateway role (MITM)."},
        ["Verify both routers see each other's hellos (show standby / show vrrp)", "Check the VLAN/trunk between them and STP state",
         "Align authentication, group number and version"],
        ["Enable FHRP authentication (MD5)", "Monitor 'MAC flapping' and FHRP state-change syslogs"], "hsrp.state == 16 || vrrp"),
    "fhrp_flap": K(
        "FHRP active router flapping", "Routing", "FHRP", "high",
        ["Hellos lost due to congestion/CPU on a router", "Preemption with object tracking toggling (uplink flapping)",
         "Priority changes from interface tracking"],
        {"client": "Every failover causes a brief outage (up to the hold time) and gratuitous-ARP churn.",
         "server": "N/A", "network": "Look for the tracked object/uplink that toggles.",
         "routing": "Frequent coups/resigns indicate instability, not a planned failover.", "application": "Micro-outages.",
         "security": "Unexpected coups can indicate a rogue router."},
        ["Correlate state changes with tracked interfaces and CPU", "Add preempt delay to prevent flapping"],
        ["Use sub-second timers only with CoPP protection; alert on state changes"], "hsrp.opcode != 0"),
    "fhrp_timer_mismatch": K(
        "FHRP timer mismatch", "Routing", "FHRP", "medium",
        ["Hello/hold (VRRP advertisement interval) configured differently"],
        {"client": "N/A", "server": "N/A", "network": "N/A",
         "routing": "The standby may declare the active dead too early or too late — unpredictable failover.",
         "application": "Longer outages during failover.", "security": "N/A"},
        ["Align timers on all group members"], ["Templates for FHRP configuration"], "hsrp || vrrp"),
    "fhrp_vip_mismatch": K(
        "FHRP virtual IP mismatch", "Routing", "FHRP", "high",
        ["Typo in 'standby ip' / 'vrrp ip' on one router"],
        {"client": "Hosts using the other VIP lose their gateway on failover.", "server": "N/A", "network": "N/A",
         "routing": "Group members disagree on the gateway address.", "application": "Outage on failover.", "security": "N/A"},
        ["Correct the virtual IP"], ["Configuration compliance checks"], "hsrp.virt_ip || vrrp.ip_addr"),
    "fhrp_auth_mismatch": K(
        "FHRP authentication mismatch", "Routing", "FHRP", "high",
        ["Different keys/modes on group members"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Members ignore each other → both become active (split brain).",
         "application": "N/A", "security": "Use MD5 authentication consistently."},
        ["Align authentication"], ["Use key chains"], "hsrp.auth_data"),
    "fhrp_weak_auth": K(
        "HSRP default cleartext authentication", "Security", "FHRP", "low",
        ["No authentication configured — HSRP sends the default string 'cisco'"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "N/A", "application": "N/A",
         "security": "Anyone on the VLAN can send a higher-priority hello and become the gateway (MITM)."},
        ["Configure MD5 authentication"], ["Harden all FHRP groups"], "hsrp.auth_data == \"cisco\""),
    "fhrp_bad_ttl": K(
        "VRRP advertisement with TTL ≠ 255", "Security", "FHRP", "medium",
        ["Packet was routed (spoofed from off-link) or a non-compliant implementation"],
        {"client": "N/A", "server": "N/A", "network": "Receivers discard these advertisements.", "routing": "Election may break.",
         "application": "N/A", "security": "Possible spoofing attempt."},
        ["Identify the sender"], ["N/A"], "vrrp && ip.ttl != 255"),
    # ================================================================ IS-IS ===
    "isis_circuit_mismatch": K(
        "IS-IS circuit-type mismatch", "Routing", "ISIS", "critical",
        ["One router is level-1-only and the other level-2-only on the same link"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "No common level → no adjacency on this link.",
         "application": "Missing routes.", "security": "N/A"},
        ["Align 'isis circuit-type' / 'is-type'"], ["Document level design per link"], "isis.hello.circuit_type"),
    "isis_area_mismatch": K(
        "IS-IS area mismatch (L1)", "Routing", "ISIS", "critical",
        ["Level-1 neighbors must share an area address; NET areas differ"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "L1 adjacency never forms.", "application": "Missing routes.", "security": "N/A"},
        ["Fix the NET area or make the link L2"], ["Plan area addressing"], "isis.area.address"),
    "isis_auth_mismatch": K(
        "IS-IS authentication mismatch", "Routing", "ISIS", "critical",
        ["Hello authentication configured on one side only or different keys/modes"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "Hellos rejected; no adjacency.", "application": "N/A",
         "security": "Use HMAC-MD5/SHA authentication consistently."},
        ["Align authentication"], ["Key chains with rollover"], "isis.auth"),
    "isis_mtu_mismatch": K(
        "IS-IS MTU mismatch (hello padding)", "Routing", "ISIS", "critical",
        ["IS-IS pads hellos to the interface MTU; neighbors have different MTUs"],
        {"client": "N/A", "server": "N/A", "network": "Large frames from the higher-MTU side are dropped by the other side.",
         "routing": "The smaller-MTU router discards the padded hellos: adjacency never comes up (or stuck INIT).",
         "application": "Missing routes.", "security": "N/A"},
        ["Match interface MTUs (preferred)"], ["Keep hello padding enabled — it detects exactly this problem"], "isis.hello"),
    "isis_one_way": K(
        "IS-IS one-way adjacency", "Routing", "ISIS", "high",
        ["Router does not receive its neighbor's hellos (unidirectional link, filtering, MTU, auth)"],
        {"client": "N/A", "server": "N/A", "network": "Check unidirectional link faults.", "routing": "Adjacency stuck in INIT.",
         "application": "N/A", "security": "N/A"},
        ["Verify hellos in both directions"], ["UDLD on fiber"], "isis.hello"),
    "isis_duplicate_sysid": K(
        "Duplicate IS-IS system ID", "Routing", "ISIS", "critical",
        ["Two routers configured with the same NET"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "routing": "LSPs overwrite each other → constant SPF churn and route flaps.",
         "application": "Intermittent reachability.", "security": "N/A"},
        ["Assign unique NETs"], ["Derive system IDs from loopback addresses"], "isis"),
    "isis_lsp_churn": K(
        "IS-IS LSP churn / purges", "Routing", "ISIS", "medium",
        ["Flapping link or adjacency", "Duplicate system IDs", "Corrupted LSPs being purged"],
        {"client": "N/A", "server": "N/A", "network": "Flapping interface.", "routing": "Frequent SPF runs; transient loops.",
         "application": "Micro-outages.", "security": "N/A"},
        ["Find the originator of the changing LSPs"], ["LSP/SPF throttling"], "isis.lsp"),
    # ================================================================= L2 ===
    "arp_duplicate_ip": K(
        "Duplicate IP address / ARP conflict", "Network", "ARP", "critical",
        ["Two hosts configured with the same IP (static inside DHCP pool)", "ARP spoofing / poisoning (MITM)",
         "Legit: FHRP/VRRP failover or NIC teaming changing MACs"],
        {"client": "Connections to that IP break intermittently as ARP caches flip between MACs.",
         "server": "If the IP is a server or gateway, traffic is misdirected.",
         "network": "Switch MAC tables will show the two MACs on different ports.",
         "application": "Random resets and timeouts.", "security": "Gateway IP claimed by an unexpected MAC is a strong ARP-spoofing indicator."},
        ["Locate both MACs in the switch MAC address table", "Correct the duplicate configuration or remove the attacker"],
        ["Enable Dynamic ARP Inspection + DHCP snooping", "Use IPAM/DHCP reservations"], "arp.duplicate-address-detected || arp.duplicate-address-frame"),
    "arp_unanswered": K(
        "Unanswered ARP requests", "Network", "ARP", "medium",
        ["Target host down or in another VLAN", "Scanning of unused addresses"],
        {"client": "Traffic to that IP cannot be delivered (host unreachable).", "server": "Target offline.",
         "network": "Check VLAN membership and host status.", "application": "N/A", "security": "Sequential ARP requests = ARP scan."},
        ["Verify the target host and VLAN"], ["Monitor ARP failures for critical IPs"], "arp.opcode == 1"),
    "arp_scan": K(
        "ARP scanning", "Security", "ARP", "medium",
        ["Host discovery (nmap -sn, netdiscover) or worm propagation"],
        {"client": "N/A", "server": "N/A", "network": "Broadcast load.", "application": "N/A", "security": "Reconnaissance on the local segment."},
        ["Identify the scanning host"], ["DAI and port security"], "arp.opcode == 1"),
    "stp_topology_change": K(
        "Spanning Tree topology changes", "Network", "STP", "medium",
        ["Access ports flapping without PortFast/edge (every host link up/down triggers a TC)", "Unstable uplink or root bridge change"],
        {"client": "Brief flooding and possible drops as MAC tables are flushed.", "server": "N/A",
         "network": "TCs flush MAC tables (short aging) → unknown-unicast flooding, CPU load on switches.",
         "application": "Micro-outages and retransmissions.", "security": "Rogue switches sending superior BPDUs can take over the root."},
        ["Find the port originating TCs (show spanning-tree detail)", "Enable PortFast/edge + BPDU guard on access ports"],
        ["Root guard on distribution; deterministic root bridge priority"], "stp.flags.tc == 1"),
    "broadcast_high": K(
        "High broadcast / multicast share", "Network", "Ethernet", "low",
        ["Large flat VLANs, chatty discovery protocols, ARP storms, loops"],
        {"client": "Every host must process broadcasts.", "server": "N/A", "network": "Layer-2 loop if extreme.",
         "application": "N/A", "security": "Broadcast storms can be a DoS."},
        ["Identify top broadcast talkers (Chris Greer 'Ethernet Broadcast' button)"], ["Segment VLANs, storm-control"], "eth.dst == ff:ff:ff:ff:ff:ff"),
    # ===================================================== multi-point ======
    "cmp_loss_between": K(
        "Packet loss located between the two capture points", "Network", "TCP", "high",
        ["A device or link between the two capture points drops packets: congested WAN link, policer, firewall/IPS, faulty optic"],
        {"client": "Sees retransmissions/stalls.", "server": "Sees retransmissions/stalls.",
         "network": "Proven: packets were seen at the upstream capture point and never arrived at the downstream one — the fault is in between.",
         "application": "Exonerated.", "security": "An inline security device between the points may be dropping."},
        ["Check interface drops/errors on every hop between the two capture points", "Add a third capture point in the middle to bisect further"],
        ["Keep the capture points permanently (TAPs) for recurring issues"], "tcp.analysis.retransmission"),
    "cmp_loss_outside": K(
        "Packet loss outside the capture points", "Network", "TCP", "medium",
        ["Loss occurs before the first or after the last capture point (on an end host, its NIC/driver, or the access link)"],
        {"client": "If the missing data never reached the first capture point, look at the sender's host/NIC/access link.",
         "server": "Same, on the server side.", "network": "The segment between the capture points is clean.",
         "application": "N/A", "security": "N/A"},
        ["Move a capture point closer to the affected host"], ["Capture on the host itself for end-to-end visibility"], "tcp.analysis.retransmission"),
    # =========================================================== Security ===
    "sec_port_scan": K(
        "TCP port scan", "Security", "TCP", "high",
        ["Reconnaissance (nmap, masscan) by attacker, pentester or inventory tool"],
        {"client": "The scanning source may be compromised or unauthorized.", "server": "Targets revealed open ports (SYN-ACK responses).",
         "network": "Many half-open connections: SYN → SYN-ACK → RST (completeness 1/3/35–37).", "application": "N/A",
         "security": "Chris Greer's 'ScanActivity' (tcp.completeness in {33..37}) and 'Open Ports' filters."},
        ["Identify and verify the source owner", "Review which ports answered (exposure)"], ["IDS scan detection, close unneeded services"],
        "tcp.completeness in {1 3 33 35 37}"),
    "sec_nmap_signature": K(
        "Nmap stealth-scan signatures", "Security", "TCP", "high",
        ["nmap -sS SYNs with window 1024 and few/no options; Null, FIN or Xmas scans"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "application": "N/A",
         "security": "Chris Greer's NMAP filter buttons: NMAPSYN_LowWin, NullScan, Xmas Scan, SYN_NOOPS."},
        ["Identify the scanner"], ["Alert on crafted-packet signatures"], "tcp.window_size_value == 1024 && tcp.flags.syn==1"),
    "sec_host_sweep": K(
        "Host sweep (one source probing many hosts)", "Security", "ICMP", "medium",
        ["Ping sweeps / discovery tools / worms"],
        {"client": "N/A", "server": "N/A", "network": "N/A", "application": "N/A", "security": "Reconnaissance."},
        ["Identify source"], ["IDS"], "icmp.type == 8"),
    "sec_cleartext_protocol": K(
        "Cleartext management/legacy protocols", "Security", "TCP", "medium",
        ["Telnet, FTP, POP3, IMAP, HTTP basic auth, SNMPv1/v2c in use"],
        {"client": "Credentials and data readable on the wire.", "server": "Exposes an insecure service.", "network": "N/A", "application": "N/A",
         "security": "Replace with SSH/SFTP/TLS variants."},
        ["Disable the cleartext service"], ["Enforce encrypted management protocols"], "telnet || ftp || pop || imap"),
    "sec_suspicious_port": K(
        "Traffic on commonly abused ports", "Security", "TCP", "medium",
        ["Reverse shells / RATs / C2 frameworks default ports (4444, 1337, 31337, 6667)"],
        {"client": "Possibly compromised.", "server": "Possibly attacker infrastructure.", "network": "N/A", "application": "N/A",
         "security": "Chris Greer's 'R-Shell' (tcp.port==1337) filter."},
        ["Inspect the payload / process owning the connection"], ["Egress filtering"], "tcp.port in {1337 4444 31337 6667}"),
    "sec_executable": K(
        "Windows executable (MZ/PE) content in traffic", "Security", "TCP", "high",
        ["Software distribution or malware download"],
        {"client": "Host received an executable.", "server": "N/A", "network": "N/A", "application": "N/A",
         "security": "Chris Greer's 'Executable Header' colouring rule ('This program cannot be run in DOS mode')."},
        ["Carve the file and check its hash"], ["Sandbox inbound executables"], "frame contains \"This program cannot be run in DOS mode\""),
    "sec_log4j": K(
        "Log4Shell (JNDI) exploit string", "Security", "HTTP", "critical",
        ["Exploit attempts for CVE-2021-44228"],
        {"client": "Attacker source.", "server": "Target may be vulnerable if it logs the header.", "network": "N/A", "application": "Patch Log4j.",
         "security": "Chris Greer's 'log4j' filter (ip contains jndi)."},
        ["Check for outbound LDAP/RMI from the target after the request", "Patch Log4j ≥2.17"], ["WAF rules"], "frame contains \"jndi\""),
}


def make(fid: str, summary: str, *, severity: str | None = None, packets=None, entities=None, ts=None,
         count: int = 1, details: dict | None = None, extra_causes=None, extra_perspectives: dict | None = None,
         title: str | None = None, filter: str | None = None) -> Finding:
    """Instantiate a finding from the knowledge base, enriched with evidence."""
    kb = KB[fid]
    persp = dict(kb["perspectives"])
    if extra_perspectives:
        for k, v in extra_perspectives.items():
            persp[k] = v + (" " + persp[k] if persp.get(k) and persp[k] != "N/A" else "")
    persp = {k: v for k, v in persp.items() if v and v != "N/A"}
    return Finding(
        id=fid, severity=severity or kb["severity"], category=kb["category"], protocol=kb["protocol"],
        title=title or kb["title"], summary=summary, packets=list(packets or []), entities=list(entities or []),
        ts=ts, count=count, details=details or {}, causes=list(extra_causes or []) + kb["causes"],
        perspectives=persp, remediation=kb["remediation"], recommendations=kb["recommendations"],
        filter=filter if filter is not None else kb["filter"],
    )
